
import java.util.Random;
import javax.swing.JOptionPane;


public class Div extends javax.swing.JFrame {
        String[] questions = new String[30];
        String[] answer = new String[30];
        Random rand = new Random();
        int count = 0;
        int num;
        int correct = 0; 


    /**
     * Creates new form Div
     */
    public Div() {
        initComponents();
        this.setTitle("BRAIN FLEX");
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jPanel1.setVisible(false);
        jPanel1.setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Division");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 79, 150, 23));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Q1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 30, 52, 48));

        jLabel3.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("0");

        jLabel4.setFont(new java.awt.Font("Snap ITC", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("---------");

        jLabel5.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HIT START!!");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 378, -1));

        jLabel7.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 76, -1));

        jLabel8.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" ");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 230, 76, -1));

        jLabel9.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" ");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 283, 76, -1));

        jLabel10.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" ");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 283, 76, -1));

        jButton1.setText("jButton1");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 378, -1));

        jButton2.setText("QUIT");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 353, 55, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         count=count+1;
         jLabel3.setText(Integer.toString(correct));
         jLabel2.setText("Q"+Integer.toString(count));
         jButton1.setVisible(false);
         jButton2.setVisible(true);
         jLabel1.setVisible(true);
         
         //Questions
         questions[0]="10/2";
         questions[1]="100/?=10";
         questions[2]="200/?=200";
         questions[3]="500/2";
         questions[4]="5/9";
         questions[5]="12/0";
         questions[6]="25/2";
         questions[7]="55/10";
         questions[8]="4/2";
         questions[9]="22/2";
         questions[10]="100/50";
         questions[11]="120/3";
         questions[12]="15/3";
         questions[13]="90/9";
         questions[14]="30/15";
         questions[15]="70/4";
         questions[16]="500/100";
         questions[17]="200/200";
         questions[18]="0/0";
         questions[19]="12/6";
         questions[20]="9/?=3";
         questions[21]="100/?=0";
         questions[22]="500/25";
         questions[23]="25/3";
         questions[24]="20/10";
         questions[25]="40/30";
         questions[26]="30/1";
         questions[27]="1/2";
         questions[28]="100/100";
         questions[29]="50/2";
         
         //Ansswers
         answer[0]="5";
         answer[1]="10";
         answer[2]="1";
         answer[3]="250";
         answer[4]="0.55";
         answer[5]="0";
         answer[6]="12.5";
         answer[7]="5.5";
         answer[8]="2";
         answer[9]="11";
         answer[10]="2";
         answer[11]="40";
         answer[12]="5";
         answer[13]="10";
         answer[14]="2";
         answer[15]="17.5";
         answer[16]="5";
         answer[17]="0";
         answer[18]="0";
         answer[19]="2";
         answer[20]="3";
         answer[21]="0";
         answer[22]="20";
         answer[23]="8.3";
         answer[24]="2";
         answer[25]="1.3";
         answer[26]="30";
         answer[27]="0.5";
         answer[28]="0";
         answer[29]="25";
       
        
         
         
         num=rand.nextInt(30);
         int j = 0;
         int[] n = new int[30];
         n[j] = num;
         j++;
         for(int i=0;i<j;i++)
         {
             while(num==n[i])
                 num=rand.nextInt(30); 
            
         }
      
         
            if(count ==1)
           {
               jPanel1.setVisible(true);
               jLabel2.setVisible(true);
               
               jLabel6.setText(questions[num]);
               jLabel10.setText(answer[num]);
               jLabel7.setText(String.valueOf((rand.nextDouble())));
               jLabel9.setText(String.valueOf((rand.nextDouble())));
               jLabel8.setText(String.valueOf((rand.nextDouble())));
               jButton1.setVisible(false);
              
           }
           else
               if((count>=2)&&(count<10))
               {
                 jPanel1.setVisible(true);
                 jLabel2.setVisible(true);
                 
                 jLabel6.setText(questions[num]);
                 jLabel9.setText(answer[num]);
                 jLabel7.setText(String.valueOf((rand.nextDouble())));
                 jLabel10.setText(String.valueOf((rand.nextDouble())));
                 jLabel7.setText(String.valueOf((rand.nextDouble())));
                 jButton1.setVisible(false);
                 
               } 
           else
                   if(count==10)
                    {
                            JOptionPane.showMessageDialog(null,"You have completed you training!!!");
                            new User().setVisible(true);
                            dispose();
                    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         if(jLabel7.getText().equals(answer[num]))
        {
           JOptionPane.showMessageDialog(null,"Correct"); 
           correct = correct + 1;
           jButton1.doClick(1);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect"); 
            JOptionPane.showMessageDialog(null,"The correct answer is\n\t"+answer[num]);
            jButton1.doClick(1);
            
        }   
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         if(jLabel8.getText().equals(answer[num]))
        {
           JOptionPane.showMessageDialog(null,"Correct"); 
           correct = correct + 1;
           jButton1.doClick(1);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect"); 
            JOptionPane.showMessageDialog(null,"The correct answer is\n\t"+answer[num]);
            jButton1.doClick(1);
            
        }   
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         if(jLabel9.getText().equals(answer[num]))
        {
           JOptionPane.showMessageDialog(null,"Correct"); 
           correct = correct + 1;
           jButton1.doClick(1);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect"); 
            JOptionPane.showMessageDialog(null,"The correct answer is\n\t"+answer[num]);
            jButton1.doClick(1);
            
        }   
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         if(jLabel10.getText().equals(answer[num]))
        {
           JOptionPane.showMessageDialog(null,"Correct"); 
           correct = correct + 1;
           jButton1.doClick(1);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect"); 
            JOptionPane.showMessageDialog(null,"The correct answer is\n\t"+answer[num]);
            jButton1.doClick(1);
            
        }   
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String res;
        if(count>=1)
        {
               res =JOptionPane.showInputDialog("You have already started the Practise\nare you sure you want quit Y/N?");
               
               while((!res.equalsIgnoreCase("Y"))&&(!res.equalsIgnoreCase("N")))
               {
                     JOptionPane.showMessageDialog(null,"Invalid please re-enter");
                     res =JOptionPane.showInputDialog("Y/N?");
               }
               if(res.equalsIgnoreCase("Y"))
               {
                   User user=new User();
                   user.setVisible(true);
                    dispose();
               }  
        }
        else
        {
            User user=new User();
            user.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Div.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Div.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Div.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Div.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Div().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
