
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Siraaj
 */
public class Multi extends javax.swing.JFrame {
        String[] questions = new String[30];
        String[] answer = new String[30];
        Random rand = new Random();
        int count = 0;
        int num;
        int correct = 0;

    /**
     * Creates new form Multi
     */
    public Multi() 
    {
        
        initComponents();
        this.setTitle("BRAIN FLEX");
        jLabel1.setVisible(false);
        jLabel11.setVisible(false);
        jPanel1.setVisible(false);
        jPanel1.setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Multiplication");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 51, 209, 47));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Q1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 56, 56));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0");

        jLabel3.setFont(new java.awt.Font("Snap ITC", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("---------");

        jLabel4.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 50, -1));

        jLabel5.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HIT START!!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 413, 70));

        jLabel6.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" ");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 234, 76, -1));

        jLabel7.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 234, 76, -1));

        jLabel8.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" ");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 285, 76, -1));

        jLabel9.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" ");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 285, 76, -1));

        jButton1.setText("START");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 331, 393, -1));

        jButton2.setText("QUIT");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 354, 60, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:count=count+1;
          count=count+1;
         jLabel2.setText(Integer.toString(correct));
         jLabel1.setText("Q"+Integer.toString(count));
         jButton1.setVisible(false);
         jButton2.setVisible(true);
         jLabel11.setVisible(true);
        
         questions[0]="5*5";
         questions[1]="10*?=100";
         questions[2]="100*200";
         questions[3]="8*?=40";
         questions[4]="1000*0";
         questions[5]="45*45";
         questions[6]="6*6";
         questions[7]="90*2";
         questions[8]="10*?=1000";
         questions[9]="50*?=500";
         questions[10]="25*10";
         questions[11]="25*25";
         questions[12]="10*10*10";
         questions[13]="65*3";
         questions[14]="3*?=9";
         questions[15]="9*10";
         questions[16]="16*16";
         questions[17]="30*2";
         questions[18]="44*3";
         questions[19]="6*6*2";
         questions[20]="15*2";
         questions[21]="3*3*3";
         questions[22]="1000*0";
         questions[23]="52*2";
         questions[24]="100*10";
         questions[25]="24*2*2";
         questions[26]="1*2";
         questions[27]="500*500*0";
         questions[28]="100*3";
         
         answer[0]="25";
         answer[1]="5";
         answer[2]="20000";
         answer[3]="5";
         answer[4]="0";
         answer[5]="135";
         answer[6]="36";
         answer[7]="180";
         answer[8]="100";
         answer[9]="10";
         answer[10]="250";
         answer[11]="625";
         answer[12]="1000";
         answer[13]="195";
         answer[14]="3";
         answer[15]="90";
         answer[16]="256";
         answer[17]="60";
         answer[18]="132";
         answer[19]="24";
         answer[20]="30";
         answer[21]="27";
         answer[22]="0";
         answer[23]="104";
         answer[24]="1000";
         answer[25]="96";
         answer[26]="2";
         answer[27]="0";
         answer[28]="300";
        
    
         num=rand.nextInt(29);
         //No repeats function
         int j = 0;
         int[] n = new int[30];
         n[j] = num;
         j++;
         for(int i=0;i<j;i++)
         {
             while(num==n[i])
                 num=rand.nextInt(30); 
            
         }
         //end
         if(count ==1)
           {
               jPanel1.setVisible(true);
               jLabel1.setVisible(true);
               
               jLabel5.setText(questions[num]);
               jLabel8.setText(answer[num]);
               jLabel6.setText(Integer.toString(rand.nextInt(100)));
               jLabel9.setText(Integer.toString(rand.nextInt(100)));
               jLabel7.setText(Integer.toString(rand.nextInt(100)));
               jButton1.setVisible(false);
              
           }
           else
               if((count>=2)&&(count<10))
               {
                 jPanel1.setVisible(true);
                 jLabel1.setVisible(true);
                 
               jLabel5.setText(questions[num]);
               jLabel8.setText(answer[num]);
               jLabel6.setText(Integer.toString(rand.nextInt(100)));
               jLabel9.setText(Integer.toString(rand.nextInt(100)));
               jLabel7.setText(Integer.toString(rand.nextInt(100)));
               jButton1.setVisible(false);
                 
               } 
           else
                   if(count==10)
                    {
                            JOptionPane.showMessageDialog(null,"You have completed you training!!!");
                            new User().setVisible(true);
                            dispose();
                    }
        
     
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
           if(jLabel6.getText().equals(answer[num]))
        {
           JOptionPane.showMessageDialog(null,"Correct"); 
           correct = correct + 1;
           jButton1.doClick(1);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect"); 
            JOptionPane.showMessageDialog(null,"The correct answer is\n\t"+answer[num]);
            jButton1.doClick(1);
            
        } 
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
           if(jLabel7.getText().equals(answer[num]))
        {
           JOptionPane.showMessageDialog(null,"Correct"); 
           correct = correct + 1;
           jButton1.doClick(1);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect"); 
            JOptionPane.showMessageDialog(null,"The correct answer is\n\t"+answer[num]);
            jButton1.doClick(1);
            
        } 
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
           if(jLabel8.getText().equals(answer[num]))
        {
           JOptionPane.showMessageDialog(null,"Correct"); 
           correct = correct + 1;
           jButton1.doClick(1);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect"); 
            JOptionPane.showMessageDialog(null,"The correct answer is\n\t"+answer[num]);
            jButton1.doClick(1);
            
        } 
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
           if(jLabel9.getText().equals(answer[num]))
        {
           JOptionPane.showMessageDialog(null,"Correct"); 
           correct = correct + 1;
           jButton1.doClick(1);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect"); 
            JOptionPane.showMessageDialog(null,"The correct answer is\n\t"+answer[num]);
            jButton1.doClick(1);
            
        } 
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String res;
        if(count>=1)
        {
               res =JOptionPane.showInputDialog("You have already started the Practise\nare you sure you want quit Y/N?");
               
               while((!res.equalsIgnoreCase("Y"))&&(!res.equalsIgnoreCase("N")))
               {
                     JOptionPane.showMessageDialog(null,"Invalid please re-enter");
                     res =JOptionPane.showInputDialog("Y/N?");
               }
               if(res.equalsIgnoreCase("Y"))
               {
                   User user=new User();
                   user.setVisible(true);
                    dispose();
               }  
        }
        else
        {
            User user=new User();
            user.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Multi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Multi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Multi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Multi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
